name: Owain94 - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - uses: actions/checkout@v2.3.1
        with:
          path: Owain94-RL-hub

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/plugins
          ref: master
          path: OpenOSRS-plugins

      - uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS-plugins

      - name: Assembling OpenOSRS plugins
        run: ./gradlew :loottracker:assemble :banktags:assemble :runepouch:assemble :emojis:assemble :cluescroll:assemble --console=plain
        working-directory: OpenOSRS-plugins

      - name: Building OpenOSRS plugins
        run: ./gradlew :loottracker:build :banktags:build :runepouch:build :emojis:build :cluescroll:build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS-plugins

      - name: Upload OpenOSRS plugins artifacts to local maven
        run: ./gradlew :loottracker:publishToMavenLocal :banktags:publishToMavenLocal :runepouch:publishToMavenLocal :emojis:publishToMavenLocal :cluescroll:publishToMavenLocal :wiki:publishToMavenLocal :slayer:publishToMavenLocal --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS-plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: Owain94-RL-hub

      - name: Assembling RL hub plugins
        run: ./gradlew assemble --console=plain
        working-directory: Owain94-RL-hub

      - name: Building RL hub plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: Owain94-RL-hub

  checkstyleMain:
    runs-on: ubuntu-latest
    name: Checkstyle main

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - uses: actions/checkout@v2.3.1
        with:
          path: Owain94-RL-hub

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/plugins
          ref: master
          path: OpenOSRS-plugins

      - uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS-plugins

      - name: Assembling OpenOSRS plugins
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS-plugins

      - name: Building OpenOSRS plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS-plugins

      - name: Upload OpenOSRS plugins artifacts to local maven
        run: ./gradlew publishToMavenLocal --console=plain
        working-directory: OpenOSRS-plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: Owain94-RL-hub

      - name: Assembling RL hub plugins
        run: ./gradlew assemble --console=plain
        working-directory: Owain94-RL-hub

      - name: Checking RL hub plugins code conventions (Main)
        run: ./gradlew checkstyleMain --console=plain
        working-directory: Owain94-RL-hub

  checkstyleTest:
    runs-on: ubuntu-latest
    name: Checkstyle test

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - uses: actions/checkout@v2.3.1
        with:
          path: Owain94-RL-hub

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/plugins
          ref: master
          path: OpenOSRS-plugins

      - uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS-plugins

      - name: Assembling OpenOSRS plugins
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS-plugins

      - name: Building OpenOSRS plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS-plugins

      - name: Upload OpenOSRS plugins artifacts to local maven
        run: ./gradlew publishToMavenLocal --console=plain
        working-directory: OpenOSRS-plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: Owain94-RL-hub

      - name: Assembling RL hub plugins
        run: ./gradlew assemble --console=plain
        working-directory: Owain94-RL-hub

      - name: Checking RL hub plugins code conventions (Test)
        run: ./gradlew checkstyleTest --console=plain
        working-directory: Owain94-RL-hub

  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bootstrap:
    runs-on: ubuntu-latest
    needs: [build, checkstyleMain, checkstyleTest]
    name: Bootstrap

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - uses: actions/checkout@v2.3.1
        with:
          path: Owain94-RL-hub

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/plugins
          ref: master
          path: OpenOSRS-plugins

      - uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS-plugins

      - name: Assembling OpenOSRS plugins
        run: ./gradlew :loottracker:assemble :banktags:assemble :runepouch:assemble :emojis:assemble :cluescroll:assemble --console=plain
        working-directory: OpenOSRS-plugins

      - name: Building OpenOSRS plugins
        run: ./gradlew :loottracker:build :banktags:build :runepouch:build :emojis:build :cluescroll:build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS-plugins

      - name: Upload OpenOSRS plugins artifacts to local maven
        run: ./gradlew :loottracker:publishToMavenLocal :banktags:publishToMavenLocal :runepouch:publishToMavenLocal :emojis:publishToMavenLocal :cluescroll:publishToMavenLocal :wiki:publishToMavenLocal :slayer:publishToMavenLocal --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS-plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: Owain94-RL-hub

      - name: Assembling RL hub plugins
        run: ./gradlew assemble --console=plain
        working-directory: Owain94-RL-hub

      - name: Building RL hub plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: Owain94-RL-hub

      - name: Bootstrapping RL hub plugins
        run: ./gradlew bootstrapPlugins --stacktrace --console=plain
        working-directory: Owain94-RL-hub

      - uses: actions/checkout@v2.3.1
        with:
          repository: Owain94/OpenOSRS-RL-hub-hosting
          ref: master
          path: Owain94-RL-hub-hosting
          token: ${{ secrets.Owain }}

      - name: Copy bootstrap
        run: cp -af /home/runner/work/OpenOSRS-RL-hub/OpenOSRS-RL-hub/Owain94-RL-hub/build/bootstrap/. /home/runner/work/OpenOSRS-RL-hub/OpenOSRS-RL-hub/Owain94-RL-hub-hosting
        working-directory: Owain94-RL-hub-hosting

      - name: Commit bootstrap
        run: |
          git add $(git ls-files -o --exclude-standard) plugins.json
          git diff-index --quiet HEAD \
          || git -c user.name="GitHub" -c user.email="noreply@github.com" commit \
            --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
            -m "Automatic plugin bootstrap"
        working-directory: Owain94-RL-hub-hosting

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.Owain }}
          directory: /home/runner/work/OpenOSRS-RL-hub/OpenOSRS-RL-hub/Owain94-RL-hub-hosting
          repository: Owain94/OpenOSRS-RL-hub-hosting
